In [1]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("C:\\Users\\srush\\OneDrive\\Desktop\\AIML Internship\\AIML-Internship\\Day 10_Data Cleaning\\raw_students.csv")
df

   StudentID          Name     Age  Gender  Score                Email
0          1      John doe      20    male   85.0     john@example.com
1          2   Jane Smith       19  Female   90.0  janesmith@email.com
2          3   Bob Johnson     NaN    Male   78.0       bobj@email.com
3          4   Alice Brown      21  Female    NaN      alice@email.com
4          5     Chris Lee  twenty    Male   88.0          chris@email
5          6      John Doe      20    Male   85.0     john@example.com
6          7           NaN      22  Female   92.0      sarah@email.com
7          8  Michael King      23    Male   75.0    michael@email.com

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  8 non-null      int64
 1   Name       7 non-null      str
 2   Age        7 non-null      str
 3   Gender     8 non-null      str
 4   Score      7 non-null      float64
 5   Email      8 non-null      str
dtypes: float64(1), int64(1), str(4)
memory usage: 516.0 bytes

In [8]:
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
df.dtypes

StudentID      int64
Name             str
Age          float64
Gender           str
Score        float64
Email            str
dtype: object

In [9]:
df

   StudentID          Name   Age  Gender  Score                Email
0          1      John doe  20.0    male   85.0     john@example.com
1          2   Jane Smith   19.0  Female   90.0  janesmith@email.com
2          3   Bob Johnson   NaN    Male   78.0       bobj@email.com
3          4   Alice Brown  21.0  Female    NaN      alice@email.com
4          5     Chris Lee   NaN    Male   88.0          chris@email
5          6      John Doe  20.0    Male   85.0     john@example.com
6          7           NaN  22.0  Female   92.0      sarah@email.com
7          8  Michael King  23.0    Male   75.0    michael@email.com

In [15]:
df.isnull().sum()

StudentID    0
Name         1
Age          2
Gender       0
Score        1
Email        0
dtype: int64

In [16]:
df["Age"]=df["Age"].fillna(value=df["Age"].mean()),inplace=True

SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='? (3427441458.py, line 1)